# Simple Home Assistant Configuration for Schulmanager Online Integration Test

# Basic configuration
homeassistant:
  name: Schulmanager Test
  latitude: 52.520008
  longitude: 13.404954
  elevation: 34
  unit_system: metric
  time_zone: Europe/Berlin
  country: DE
  currency: EUR
  internal_url: "http://localhost:8123"
  
  # Allow loading custom integrations
  allowlist_external_dirs:
    - /config/custom_components

# Default config
default_config:

# Enable frontend
frontend:
  themes: !include_dir_merge_named themes

# Enable Lovelace UI
lovelace:
  mode: storage
  # Add our custom card resources
  resources:
    - url: /local/schulmanager-schedule-card.js
      type: module

# HTTP configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# Logger configuration
logger:
  default: info
  logs:
    custom_components.schulmanager_online: debug
    homeassistant.components.sensor: info
    homeassistant.components.calendar: info

# Recorder (use SQLite instead of PostgreSQL)
recorder:
  db_url: sqlite:////config/home-assistant_v2.db
  purge_keep_days: 5
  commit_interval: 1

# History
history:
  include:
    domains:
      - sensor
      - calendar
    entity_globs:
      - sensor.schulmanager_*

# Logbook
logbook:
  include:
    domains:
      - sensor
      - calendar
    entity_globs:
      - sensor.schulmanager_*

# System Health
system_health:

# My Home Assistant
my:

# Mobile App
mobile_app:

# Person
person:

# Zone
zone:

# Sun
sun:

# Weather
weather:

# Map
map:

# Energy
energy:

# Automation
automation: !include automations.yaml

# Script
script: !include scripts.yaml

# Scene
scene: !include scenes.yaml

# Input Boolean
input_boolean:

# Input Number  
input_number:

# Input Select
input_select:

# Input Text
input_text:

# Input Datetime
input_datetime:

# Timer
timer:

# Counter
counter:
